safe: false
port: 4000
base-url:    /

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date

kramdown:
  input: GFM
  auto_ids: true,
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge


    
  syntax_highlighter_opts:
    block: 
      disable: true
    span:
      wrap: i
      line_numbers: false
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style
